### ISSUE TITLE
🐞 Duplicate emails should not be allowed

### ISSUE THREAD

**Issue by jontyk** [openline-ai/openline-customer-os#536] opened 2023-01-04 17:23 UTC
**Describe the bug**
It is possible to create duplicate emails (see current dev environment). This should not be possible and should error correctly.

**Expected behavior**
Email should be unique per email per tenant (i.e. bob@krispykreme.com should be able to exist against multiple tenants, but only once)

Thank you for your bug report!  We ❤️ squashing 🪲

**Comment by edifirut** [comment] 2023-01-27 14:27
duplicate of https://github.com/openline-ai/openline-customer-os/issues/177

**Closed as not planned by edifirut** 2023-01-27 14:27 UTC
Labels: bug, app/customer-os-api, app/sync-customer-os-data, app/sync-tracked-data
