### ISSUE TITLE
Edit email/phone number not working

### ISSUE THREAD

**Issue by jontyk** [openline-ai/openline-customer-os#1182] opened 2023-03-07 11:38 UTC
Thank you for your bug report!  We ❤️ squashing 🪲

**Comment by Kasia9090** [comment] 2023-03-08 08:50
@jontyk can you provide more information on how to reproduce this issue?

FYI: currently user can edit only label and primary property for email and contact. Please see the issue https://github.com/openline-ai/openline-customer-os/issues/1125

**Comment by alexopenline** [comment] 2023-03-08 09:33
BE issue opened: https://github.com/openline-ai/openline-customer-os/issues/1148

**Comment by avalot** [comment] 2023-03-08 17:38
Duplicate of https://github.com/openline-ai/openline-customer-os/issues/1125

**Closed as not planned by avalot** 2023-03-08 17:38 UTC
Labels: bug

**Comment by alexopenline** [comment] 2023-03-08 17:46
update API enhanced with change or email / phone number: https://github.com/openline-ai/openline-customer-os/issues/1148
