### ISSUE TITLE
Clearing search does not work

### ISSUE THREAD

**Issue by avalot** [openline-ai/openline-customer-os#1195] opened 2023-03-07 20:18 UTC
**Describe the bug**
When you clear out the search key, the list does not go back to its initial state.

Let's make sure that we revert to the initial list when the search keys are cleared (worst case scenario, force a reload)

Thank you for your bug report!  We ❤️ squashing 🪲

**Comment by Kasia9090** [comment] 2023-03-08 08:16
I can'r reproduce the issue on any of the environments, please see https://www.loom.com/share/4d51d70c7fc64b38a0f51bc240bca715
Please check if the issue is still present on your end

**Comment by Kasia9090** [comment] 2023-03-09 09:55
Closing because it's no longer reproducible

**Closed as completed by Kasia9090** 2023-03-09 09:55 UTC
Labels: bug
