### ISSUE TITLE
Contact moved jobs use case

### ISSUE THREAD

**Issue by mattbr0wn** [openline-ai/openline-customer-os#977] opened 2023-02-22 12:41 UTC
- Contact A is in our system with an email associated with [acme.com](http://acme.com/) (acme corp)
- A has since left acme corp and started new job with [beta.com](http://beta.com/) (beta corp)
- I'd like to archive A's [acme.com](http://acme.com/) email address (so we keep previous email history), add Beta Corp as an org, and add new beta corp email for future tracking

Link to example: https://spaces.openline.ai/contact/21c9d463-74a5-43bc-b39b-d66654a8e848

**Comment by avalot** [comment] 2023-02-22 13:58
In theory that’s a no brainer: 

- In the contact’s timeline, the new job relationship with the new org is an event. All convos before and after that event are there, no impact.
- In ACME corp’s timeline, convos show up until the moment of the job-switch. Any emails with acme.com, even after the switch, would still show up
- In BETA’s timeline, all convos after the switch show up, except emails to acme.com address.

The problem is in the case of double-jobbing. E.G. consultant X who works for both ACME and BETA at the same time. We can split along separate emails, but for other channels (or if using a non-acme, non-beta address), we have a conundrum.

Obvious fix: 

1. We need an Assignment Engine, that will analyze the convos that involve multi-job contacts, and attempt to auto-assign them to the right org. 
2. We should mark convos that were auto-assigned with low confidence, and perhaps add them to the user’s Quick Fix notifications, to review and reassign as needed.
3. In the timelines, users should always have the ability to reassign conversations to Org A or Org B.

**Closed as not planned** 2023-09-14 08:06 UTC
Labels: feature request
